version: '3.3'

services:
  nginx:
    container_name: nginx
    image: nginx:1.25.3-alpine
    ports:
      - '80:80'
    volumes:
      # frontend volume
      - ./src/$FRONTEND_FOLDER:/var/www/html/frontend
      # laravel api volume
      - ./src/$BACKEND_FOLDER:/var/www/html/api
      # nginx main config
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # other nginx config
      - ./nginx/conf.d:/etc/nginx/conf.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`$MAIN_DOMAIN`)"
      - "traefik.http.routers.nginx.entrypoints=https"
      - "traefik.http.routers.nginx.tls.certresolver=letsencrypt-production"
      - "traefik.http.routers.nginx.tls=true"
    networks:
      - traefik_network

  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
    volumes:
      # laravel api volume
      - ./src/$BACKEND_FOLDER:/var/www/html/api
      # raw php volume
      - ./src/$PHP_FOLDER:/var/www/html/php
    networks:
      - mariadb_network
      - traefik_network

networks:
  traefik_network:
    external: true
  mariadb_network:
    external: true
